# HTTP Port
quarkus.http.port=9090

# MySQL Datasource
#quarkus.datasource.db-kind=mysql
#quarkus.datasource.db-version=5.7.24
#quarkus.datasource.jdbc.url=jdbc:mysql://192.168.5.215:3306/gjk_eform?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
#quarkus.datasource.username=dev
#quarkus.datasource.password=123456

# Hibernate ORM
quarkus.hibernate-orm.active=false
#quarkus.hibernate-orm.database.generation=none
#quarkus.hibernate-orm.log.sql=true
